/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv functions/cloudflare-env.d.ts` (hash: f37eb36330b23b33a772501b23af2752)
interface __BaseEnv_CloudflareEnv {
	COMMENTS_DB: D1Database;
	SEARCH_RATE_LIMIT_DB: D1Database;
	SEARCH_INDEX: VectorizeIndex;
	AI: Ai;
	CLOUDFLARE_ACCOUNT_ID: "db9b62f409f463da7acbcc374b8385d0";
	CLOUDFLARE_AI_MODEL: "@cf/zai-org/glm-5.2";
	CLOUDFLARE_AI_REASONING_EFFORT: "low";
	COMMENT_ALLOWED_HOSTNAMES: "acecore.net,www.acecore.net,acecore-net.pages.dev" | "acecore.net,www.acecore.net,acecore-net.pages.dev,localhost,127.0.0.1";
	CONTACT_FROM_EMAIL: "noreply@acecore.net";
	CONTACT_TO_EMAIL: "info@acecore.net";
	CONTACT_ALLOWED_HOSTNAMES: "acecore.net,www.acecore.net,acecore-net.pages.dev,systems.acecore.net" | "acecore.net,www.acecore.net,acecore-net.pages.dev,systems.acecore.net,localhost,127.0.0.1";
	SEARCH_ENABLED: "true";
	SEARCH_MIN_SCORE: "0.50";
}
declare namespace Cloudflare {
	interface PreviewEnv {
		COMMENTS_DB: D1Database;
		SEARCH_RATE_LIMIT_DB: D1Database;
		SEARCH_INDEX: VectorizeIndex;
		AI: Ai;
		CLOUDFLARE_ACCOUNT_ID: "db9b62f409f463da7acbcc374b8385d0";
		CLOUDFLARE_AI_MODEL: "@cf/zai-org/glm-5.2";
		CLOUDFLARE_AI_REASONING_EFFORT: "low";
		COMMENT_ALLOWED_HOSTNAMES: "acecore.net,www.acecore.net,acecore-net.pages.dev";
		CONTACT_FROM_EMAIL: "noreply@acecore.net";
		CONTACT_TO_EMAIL: "info@acecore.net";
		CONTACT_ALLOWED_HOSTNAMES: "acecore.net,www.acecore.net,acecore-net.pages.dev,systems.acecore.net";
		SEARCH_ENABLED: "true";
		SEARCH_MIN_SCORE: "0.50";
	}
	interface ProductionEnv {
		COMMENTS_DB: D1Database;
		SEARCH_RATE_LIMIT_DB: D1Database;
		SEARCH_INDEX: VectorizeIndex;
		AI: Ai;
		CLOUDFLARE_ACCOUNT_ID: "db9b62f409f463da7acbcc374b8385d0";
		CLOUDFLARE_AI_MODEL: "@cf/zai-org/glm-5.2";
		CLOUDFLARE_AI_REASONING_EFFORT: "low";
		COMMENT_ALLOWED_HOSTNAMES: "acecore.net,www.acecore.net,acecore-net.pages.dev";
		CONTACT_FROM_EMAIL: "noreply@acecore.net";
		CONTACT_TO_EMAIL: "info@acecore.net";
		CONTACT_ALLOWED_HOSTNAMES: "acecore.net,www.acecore.net,acecore-net.pages.dev,systems.acecore.net";
		SEARCH_ENABLED: "true";
		SEARCH_MIN_SCORE: "0.50";
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
