content:
  - name: blog
    label: ブログ
    path: src/content/blog
    type: collection
    view:
      fields: [title, date, author]
      sort: date
      order: desc
    fields:
      - name: title
        label: タイトル
        type: string
        required: true
      - name: description
        label: 概要
        type: text
        required: true
      - name: date
        label: 公開日
        type: date
        required: true
      - name: tags
        label: タグ
        type: string
        list: true
      - name: imageUrl
        label: 画像URL
        type: string
      - name: author
        label: 著者
        type: string
      - name: body
        label: 本文
        type: rich-text

media:
  input: public/uploads
  output: /uploads
