/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/sveltia-cms-auth/wrangler.jsonc --include-runtime=false --env-interface=SveltiaCmsAuthConfig workers/sveltia-cms-auth/worker-configuration.d.ts` (hash: 7f552fb7b35da7d7db9ad2cfdd252d29)
interface __BaseEnv_SveltiaCmsAuthConfig {
	GITHUB_CLIENT_SECRET_STORE: SecretsStoreSecret;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_SveltiaCmsAuthConfig {}
}
interface SveltiaCmsAuthConfig extends __BaseEnv_SveltiaCmsAuthConfig {}
