/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/sveltia-cms-auth/wrangler.jsonc --include-runtime=false --env-interface=SveltiaCmsAuthConfig workers/sveltia-cms-auth/worker-configuration.d.ts` (hash: 800b3feee5a0bf44e05643efc76c2148)
interface __BaseEnv_SveltiaCmsAuthConfig {
	GITHUB_CLIENT_SECRET_STORE: SecretsStoreSecret;
	ALLOWED_DOMAINS: "acecore.net,*.acecore-net.pages.dev,localhost,localhost:4321,127.0.0.1";
	GITHUB_SCOPE: "repo,user";
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_SveltiaCmsAuthConfig {}
}
interface SveltiaCmsAuthConfig extends __BaseEnv_SveltiaCmsAuthConfig {}
