/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/sveltia-cms-auth/wrangler.jsonc --include-runtime=false --env-interface=SveltiaCmsAuthConfig workers/sveltia-cms-auth/worker-configuration.d.ts` (hash: 81301c31f204a2b04a938ed840fca02a)
interface __BaseEnv_SveltiaCmsAuthConfig {
	ALLOWED_DOMAINS: "acecore.net,*.acecore-net.pages.dev,localhost,localhost:4321,127.0.0.1";
	GITHUB_SCOPE: "repo,user";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_SveltiaCmsAuthConfig {}
}
interface SveltiaCmsAuthConfig extends __BaseEnv_SveltiaCmsAuthConfig {}
