/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/contact-email/wrangler.jsonc --include-runtime=false --env-interface=ContactEmailConfig workers/contact-email/worker-configuration.d.ts` (hash: 2a7c888707ee6785c60b763dd163a708)
interface __BaseEnv_ContactEmailConfig {
	EMAIL: SendEmail;
	CONTACT_FROM_EMAIL: "noreply@acecore.net";
	CONTACT_TO_EMAIL: "info@acecore.net";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface PreviewEnv {
		EMAIL: SendEmail;
		CONTACT_FROM_EMAIL: "noreply@acecore.net";
		CONTACT_TO_EMAIL: "info@acecore.net";
	}
	interface ProductionEnv {
		EMAIL: SendEmail;
		CONTACT_FROM_EMAIL: "noreply@acecore.net";
		CONTACT_TO_EMAIL: "info@acecore.net";
	}
	interface Env extends __BaseEnv_ContactEmailConfig {}
}
interface ContactEmailConfig extends __BaseEnv_ContactEmailConfig {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CONTACT_FROM_EMAIL" | "CONTACT_TO_EMAIL">> {}
}
